### ISSUE TITLE
About the test accuracy metric

### ISSUE THREAD

**Issue by bloodyhead** [shengliu66/SOP#4]
Dear Liu:

Thanks for your work! I have a question that if the test accuracy of SOP+ reported in paper (Table 2) is computed with the model of the last epoch(300-epoch model) or with the best-accuracy epoch before the last epoch. I run your code with your default settings but got the best result in the 292nd epoch instead of the last epoch. Furthermore, the test acc in our experiment is only 78.49 with 20% symmetric noise label which is lower than 78.8 reported in the paper. I wonder if there is anything wrong with my training.

Thank you for your help!

**Comment by shengliu66** [comment]
Thank you for the questions, we follow the previous literature to report the max averaged test accuracy, the result you obtained in very close, the difference might because of the training process contains randomness.

**Comment by bloodyhead** [comment]
Thank you for your help!
