### ISSUE TITLE
performance of different code version

### ISSUE THREAD

**Issue by bloodyhead** [shengliu66/SOP#8]
Dear Liu:

Thanks for your work! 

When I run your code, the version you commited on Jun 2 can perform as you reported in paper on symmetric cases but has bad performance on asymmetric cases. However, the latest version has the same performance as repored in paper on asymmetric cases but has bad test accuracy (reported 75.9 but our result is only 45.66 on sym-80%,CIFAR-100) on symmetric cases.

Is there any version of your code that can reach the performance reported in paper in both symmetric and asymmetric cases?

thank you for your help!

**Comment by shengliu66** [comment]
Thanks for pointing out this, we found out the issue, please try the updated code and the readme. Thank you!
