### ISSUE TITLE
What is the hyper-parameters for SOP+ in table.2?

### ISSUE THREAD

**Issue by 1292224662** [shengliu66/SOP#9]
Hi, I noted that in table.2, the backbone for SOP+ is Res34.

However, in the table A.4 (table of hyper-parameters), it is shown that all Res34 have lambda_C = lambda_B = 0. It really confused me since SOP+ with  lambda_C = lambda_B = 0 is simply SOP.

Am I make something wrong? Or the SOP+ in table.2 is in fact simply SOP? Or there are some others hyper-parameters differing from table A.4?

**Comment by 1292224662** [comment]
What's more, is SOP+ consistently better than SOP in your experiments or SOP+ may perform worse sometimes?

It would be appreciate if you could share some experience on it.

**Comment by shengliu66** [comment]
Nice catch! It was a mistake and for the architecture for Table 2 we use preactresnet18. We will update the paper. Thank you and sorry for the confusion. I believe when the dataset is highly imbalanced adding the regularization could be worse but we didn't run any experiments to confirm this.
